[package]
name = "room"
version = "1.0.0"
edition = "2021"
authors = ["Fernando Vega <pytness@gmail.com>"]
publish = false

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.26"
owo-colors = "4.0.0"
zellij-tile = "0.41.1"
